language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: SJ60iVjYcE3ZrY/K6lWNDMQ5UFe/WSufMtoygoqAxyI+ETjurlOPr+WrgvTYjNgwllLzMm1eKJWMG66TR3s+1zZQn7QCqhOxTB4YDWzupgAsaWaXbqloHXymLXOq+R3RZVX2guqGFRdr18grTXdG/5z8/cWdt29df4VJ0DPldG4iPTZVcgWpdU7VdmAl814KStBbazFzjZiHCXYf/YEoFaMyHxEPSKYkXCiKEj/AnPeh0tU6tffRBFFa3YQY1YpNIJy9rWNQ/l6DXv2WS4LC62oNM9T9C+I0JNTtRtqzo+fT5lw+2IgK/QWHM1F8PZQLPFN/ONERwTjr31TDlvo4IjeDjvgLTjHEOgKwdwP4hqdeqGmVMK4lmh340uJASBDrQzCAaxsuIoDXsP8i7x9pB7isMIouqbhTUJiqIZbYlbmrIsJtH5rTNqFoBNJRiUxrFbr8CACU09vZITKhyYnGu9EwrYzVh3Jq3hnDnrBaeGw6kX0ypuidFCGL5E4qzOPph2CWNsi963Cy9re9C0GEkjpMP13E3cjtp38gec1KWUId9yDYB6CDy22lwk8bhSOmFQV8b2wAAUMo51Xq1MPHzMMYwFXckMUfeQ0Wi9yRvnSsy0boEH5jm/5P+RzmjEL4S/jg00lsxLkN/Ls4fuglsr/9NwLw38vPZ//+BpT4cWU=
  file: "target/jmeter-iso8583-*.jar"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: tilln/jmeter-iso8583
    tags: true
